# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_app', '0002_auto_20160224_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasystat',
            name='weekly_points',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
